version: '3'

services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    command: python src/server.py
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    links:
      - backend
    command: npm start